# Cloudflare Pages Configuration
[build]
  command = "npm ci && npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "22.15.1"
  NPM_VERSION = "10.9.2"
  NODE_ENV = "production"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Country = ["US", "GB", "CA", "AU"]}

# Headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "text/javascript"
    Cache-Control = "public, max-age=86400" 