name = "zero-core-studio"
compatibility_date = "2024-12-19"

# Cloudflare Pages için build konfigürasyonu
[build]
command = "npm ci && npm run build"
cwd = "."
watch_dir = ["src", "public"]

# Static dosyalar için output dizini
[build.upload]
format = "directory"
dir = "out"

# Environment variables
[env]
NODE_VERSION = "22.15.1"
NPM_VERSION = "10.9.2"
YARN_ENABLED = "false"
SKIP_YARN_COREPACK = "true"

# Development environment
[env.development]
NODE_ENV = "development"

# Production environment  
[env.production]
NODE_ENV = "production"

# Pages specific settings
[pages]
build_output_directory = "out"
preview_directory = "out" 